### ISSUE TITLE
Network glitches cause mayhem after move_it_server is left in a bad state

### ISSUE THREAD

**Issue by mraspaud** [pytroll/trollmoves#10]
The server keeps on publishing files but is unable to process requests.

**Comment by TAlonglong** [comment]
Not sure if this is related.

But I see some messages like this (Sorry for the time confusion, server has CET log time stamps, client has UTC log time stamps:

Server side:
[2018-02-27 13:58:09,119 ERROR    trollmoves.server] Something went wrong during copy of /data/unpack/H-000-MSG4__-MSG4________-IR_097___-000007___-201802271245-__ to ftp://satproc2/data2/geo-proc/incoming-dir/H-000-MSG4__-MSG4________-IR_097___-000007___-201802271245-__: [Errno -2] Name or service not known
[2018-02-27 13:58:09,119 DEBUG    trollmoves.server]   File "/home/eumetcast/.local/lib/python2.7/site-packages/trollmoves-0.1.1-py2.7.egg/trollmoves/server.py", line 548, in move_it
    mover(pathname, dest_url, attrs=attrs).copy()
  File "/home/eumetcast/.local/lib/python2.7/site-packages/trollmoves-0.1.1-py2.7.egg/trollmoves/server.py", line 625, in copy
    21)
  File "/usr/lib/python2.7/ftplib.py", line 135, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):



Client side:
[2018-02-27 12:58:09,135 DEBUG   ] Receiving (REQ) pytroll://1b/hrit-segment/0deg err eumetcast@sater5 2018-02-27T12:58:09.120003 v1.01 text/ascii 
[Errno -2] Name or service not known
[2018-02-27 12:58:09,135 ERROR   ] Failed to get valid response from server 157.249.16.182: pytroll://1b/hrit-segment/0deg err eumetcast@sater5 201
8-02-27T12:58:09.120003 v1.01 text/ascii [Errno -2] Name or service not known

So I guess it is related to problems getting translated the host name to an ip?

**Comment by TAlonglong** [comment]
OK.
This is my test:

3000 1Byte files with message size 11682Bytes. I did the message size huge so provoke me guess filling up the socket.

It took less than 10 seconds for the server to match all files and send all 3000 messages,
Then over the lunch, approx 30 minutes after I sent the messages I got:
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/eumetcast/.local/lib/python2.7/site-packages/trollmoves-0.1.1-py2.7.egg/trollmoves/server.py", line 225, in run
    message = Message(rawstr=payload)
  File "/home/eumetcast/.local/lib/python2.7/site-packages/posttroll-1.3.0-py2.7.egg/posttroll/message.py", line 119, in __init__
    self.__dict__ = _decode(rawstr)
  File "/home/eumetcast/.local/lib/python2.7/site-packages/posttroll-1.3.0-py2.7.egg/posttroll/message.py", line 238, in _decode
    % _MAGICK)
MessageError: This is not a 'pytroll:/' message (wrong magick word)

This was just after file and message number 1565. That means aprox 18MB of total messages.

This is of course much more than the system was intended for, I guess. But anyway this is what I experience.

**Comment by TAlonglong** [comment]
So

I though I did a isolated test. I set up a separate server with its own port and a separate client.

But ( I dont know which failed first) all my other server and client stopped working around the same time my test failed, with like:
Exception in thread Thread-50:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/eumetcast/.local/lib/python2.7/site-packages/trollmoves-0.1.1-py2.7.egg/trollmoves/server.py", line 224, in run
    NOBLOCK)
ValueError: need more than 2 values to unpack

Exception in thread Thread-68:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/eumetcast/.local/lib/python2.7/site-packages/trollmoves-0.1.1-py2.7.egg/trollmoves/server.py", line 224, in run
    NOBLOCK)
ValueError: need more than 2 values to unpack

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/eumetcast/.local/lib/python2.7/site-packages/trollmoves-0.1.1-py2.7.egg/trollmoves/server.py", line 225, in run
    message = Message(rawstr=payload)
  File "/home/eumetcast/.local/lib/python2.7/site-packages/posttroll-1.3.0-py2.7.egg/posttroll/message.py", line 119, in __init__
    self.__dict__ = _decode(rawstr)
  File "/home/eumetcast/.local/lib/python2.7/site-packages/posttroll-1.3.0-py2.7.egg/posttroll/message.py", line 238, in _decode
    % _MAGICK)
MessageError: This is not a 'pytroll:/' message (wrong magick word)

**Comment by pnuu** [comment]
This brought to my mind our "too many files open" problem we had with `move_it.py`. The cause was that every mover created a publisher for _each_ separate item in the config if the publish topic was set. All the subscirebers within reach then created connections to _all_ of these publishers, even if they weren't actually interested about the topic being published. So there were something like gazillion connections open at the same time.
