### ISSUE TITLE
Possible to handle messages with dataset

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/trollmoves#107]
## Feature Request

Is it possible to make the server/client handle dataset?

It looks like its working but the client fails with eg:
```
Dec 01 20:09:09 ppi-adm-a2 move_it_client.py[6873]: [2021-12-01 20:09:09,443 DEBUG    trollmoves.client] Sending a public 'ack' of completed transfer: pytroll://PPSV2021/EARS/PRODUCTS ack remotesensing@pp
i-adm-a2 2021-12-01T20:09:09.443078 v1.01 application/json {"antenna": "ears", "publish_topic": "/PPS-V2021/ears/processed", "station": "Oslo", "variant": "EARS", "geo_or_polar": "polar", "software": "NWC
SAF-PPSv2021", "nameservers": ["192.168.10.9"], "module": "ppsCmaskPrepare", "pps_version": "v2021", "platform_name": "Metop-B", "orbit": 0, "sensor": "avhrr", "start_time": "2021-12-01T20:00:00", "end_ti
me": "2021-12-01T20:00:59.800000", "file_was_already_processed": false, "status": "OK", "dataset": [{"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/ANC_remapped/S_NWC_thresholds_metopb_00000_2
0211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_thresholds_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}, {"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/ANC_remapped/S_NWC_textu
res_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_textures_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}, {"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/EMISS_re
mapped/S_NWC_emissivity_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_emissivity_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}, {"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf
/intermediate/IMAGER_remapped/S_NWC_37refl_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_37refl_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}], "data_processing_level": "2", 
"format": "CF", "request_address": "157.249.98.10:9301"}
Dec 01 20:09:09 ppi-adm-a2 move_it_client.py[6873]: [2021-12-01 20:09:09,444 ERROR    trollmoves.client] Listener died.
Dec 01 20:09:09 ppi-adm-a2 move_it_client.py[6873]: Traceback (most recent call last):
Dec 01 20:09:09 ppi-adm-a2 move_it_client.py[6873]:   File "/home/remotesensing/miniconda3-bionic/envs/pytroll/lib/python3.8/site-packages/trollmoves/client.py", line 231, in run
Dec 01 20:09:09 ppi-adm-a2 move_it_client.py[6873]:     self.callback(msg, *self.cargs, **self.ckwargs)
Dec 01 20:09:09 ppi-adm-a2 move_it_client.py[6873]:   File "/home/remotesensing/miniconda3-bionic/envs/pytroll/lib/python3.8/site-packages/trollmoves/client.py", line 599, in request_push
Dec 01 20:09:09 ppi-adm-a2 move_it_client.py[6873]:     lmsg = replace_mda(lmsg, kwargs)
Dec 01 20:09:09 ppi-adm-a2 move_it_client.py[6873]:   File "/home/remotesensing/miniconda3-bionic/envs/pytroll/lib/python3.8/site-packages/trollmoves/client.py", line 446, in replace_mda
Dec 01 20:09:09 ppi-adm-a2 move_it_client.py[6873]:     replacement = dict(item.split(':')
Dec 01 20:09:09 ppi-adm-a2 move_it_client.py[6873]: ValueError: dictionary update sequence element #0 has length 1; 2 is required
Dec 01 20:09:09 ppi-adm-a2 move_it_client.py[6873]: [2021-12-01 20:09:09,445 ERROR    trollmoves.client] Listener for tcp://157.249.98.10:9960 died 2 times: dictionary update sequence element #0 has lengt
h 1; 2 is required
```

So either we need to skip handelig of dataset, print a warning and skipping the message on the server side.

Or we need to make it work,

My server log looks like this, so it do copy the various files:
```
[2021-12-01 20:09:04,680 DEBUG    trollmoves.server] We have a match: pytroll://PPS-V2021/ears/processed dataset ubuntu@pps-v2021-a 2021-12-01T20:08:57.941623 v1.01 application/json {"publish_topic": "/PPS-V2021/ears/processed", "station": "Oslo", "variant": "EARS", "geo_or_polar": "polar", "software": "NWCSAF-PPSv2021", "nameservers": ["192.168.10.9"], "module": "ppsCmaskPrepare", "pps_version": "v2021", "platform_name": "Metop-B", "orbit": 0, "sensor": "avhrr", "start_time": "2021-12-01T20:00:00", "end_time": "2021-12-01T20:00:59.800000", "file_was_already_processed": false, "status": "OK", "dataset": [{"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/ANC_remapped/S_NWC_thresholds_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_thresholds_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}, {"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/ANC_remapped/S_NWC_textures_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_textures_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}, {"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/EMISS_remapped/S_NWC_emissivity_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_emissivity_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}, {"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/IMAGER_remapped/S_NWC_37refl_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_37refl_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}], "data_processing_level": "2", "format": "CF"}
[2021-12-01 20:09:04,681 DEBUG    trollmoves.server] Message sent: pytroll://PPSV2021/EARS/PRODUCTS dataset ubuntu@pps-v2021-a 2021-12-01T20:09:04.680958 v1.01 application/json {"antenna": "ears", "publish_topic": "/PPS-V2021/ears/processed", "station": "Oslo", "variant": "EARS", "geo_or_polar": "polar", "software": "NWCSAF-PPSv2021", "nameservers": ["192.168.10.9"], "module": "ppsCmaskPrepare", "pps_version": "v2021", "platform_name": "Metop-B", "orbit": 0, "sensor": "avhrr", "start_time": "2021-12-01T20:00:00", "end_time": "2021-12-01T20:00:59.800000", "file_was_already_processed": false, "status": "OK", "dataset": [{"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/ANC_remapped/S_NWC_thresholds_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_thresholds_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}, {"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/ANC_remapped/S_NWC_textures_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_textures_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}, {"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/EMISS_remapped/S_NWC_emissivity_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_emissivity_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}, {"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/IMAGER_remapped/S_NWC_37refl_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_37refl_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}], "data_processing_level": "2", "format": "CF", "request_address": "157.249.98.10:9301"}
[2021-12-01 20:09:04,690 DEBUG    trollmoves.server] Received a request
[2021-12-01 20:09:04,693 DEBUG    trollmoves.server] processing request: pytroll://PPSV2021/EARS/PRODUCTS push remotesensing@ppi-adm-a2 2021-12-01T20:09:08.837485 v1.01 application/json {"antenna": "ears", "publish_topic": "/PPS-V2021/ears/processed", "station": "Oslo", "variant": "EARS", "geo_or_polar": "polar", "software": "NWCSAF-PPSv2021", "nameservers": ["192.168.10.9"], "module": "ppsCmaskPrepare", "pps_version": "v2021", "platform_name": "Metop-B", "orbit": 0, "sensor": "avhrr", "start_time": "2021-12-01T20:00:00", "end_time": "2021-12-01T20:00:59.800000", "file_was_already_processed": false, "status": "OK", "dataset": [{"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/ANC_remapped/S_NWC_thresholds_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_thresholds_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}, {"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/ANC_remapped/S_NWC_textures_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_textures_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}, {"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/EMISS_remapped/S_NWC_emissivity_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_emissivity_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}, {"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/IMAGER_remapped/S_NWC_37refl_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_37refl_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}], "data_processing_level": "2", "format": "CF", "request_address": "157.249.98.10:9301", "destination": "scp://157.249.160.122/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf"}
[2021-12-01 20:09:04,694 DEBUG    trollmoves.movers] new_dest = ParseResult(scheme='scp', netloc='remotesensing@157.249.160.122', path='/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf', params='', query='', fragment='')
[2021-12-01 20:09:04,694 DEBUG    trollmoves.movers] Copying to: scp://157.249.160.122/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf
[2021-12-01 20:09:04,695 DEBUG    trollmoves.movers] Scheme = scp
[2021-12-01 20:09:04,695 DEBUG    trollmoves.movers] Destination: ParseResult(scheme='scp', netloc='remotesensing@157.249.160.122', path='/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf', params='', query='', fragment='')
[2021-12-01 20:09:04,695 DEBUG    trollmoves.movers] Destination username and passwd: remotesensing None
[2021-12-01 20:09:04,695 DEBUG    trollmoves.movers] Getting connection to remotesensing@157.249.160.122:22
[2021-12-01 20:09:04,695 DEBUG    trollmoves.movers] checking ssh connection
[2021-12-01 20:09:04,695 DEBUG    trollmoves.movers] SSH connection is active.
[2021-12-01 20:09:04,696 DEBUG    paramiko.transport] [chan 15] Max packet in: 32768 bytes
[2021-12-01 20:09:04,699 DEBUG    paramiko.transport] [chan 15] Max packet out: 32768 bytes
[2021-12-01 20:09:04,699 DEBUG    paramiko.transport] Secsh channel 15 opened.
[2021-12-01 20:09:04,702 DEBUG    paramiko.transport] [chan 15] Sesch channel 15 request ok
[2021-12-01 20:09:04,843 DEBUG    paramiko.transport] [chan 15] EOF sent (15)
[2021-12-01 20:09:04,844 INFO     trollmoves.movers] Successfully copied /data/pytroll/nwcsaf/intermediate/ANC_remapped/S_NWC_thresholds_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc to scp://157.249.160.122/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf
[2021-12-01 20:09:04,845 DEBUG    trollmoves.movers] new_dest = ParseResult(scheme='scp', netloc='remotesensing@157.249.160.122', path='/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf', params='', query='', fragment='')
[2021-12-01 20:09:04,845 DEBUG    trollmoves.movers] Copying to: scp://157.249.160.122/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf
[2021-12-01 20:09:04,845 DEBUG    trollmoves.movers] Scheme = scp
[2021-12-01 20:09:04,845 DEBUG    trollmoves.movers] Destination: ParseResult(scheme='scp', netloc='remotesensing@157.249.160.122', path='/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf', params='', query='', fragment='')
[2021-12-01 20:09:04,845 DEBUG    trollmoves.movers] Destination username and passwd: remotesensing None
[2021-12-01 20:09:04,846 DEBUG    trollmoves.movers] Getting connection to remotesensing@157.249.160.122:22
[2021-12-01 20:09:04,846 DEBUG    trollmoves.movers] checking ssh connection
[2021-12-01 20:09:04,846 DEBUG    trollmoves.movers] SSH connection is active.
[2021-12-01 20:09:04,847 DEBUG    paramiko.transport] [chan 16] Max packet in: 32768 bytes
[2021-12-01 20:09:04,848 DEBUG    paramiko.transport] [chan 15] EOF received (15)
[2021-12-01 20:09:04,876 DEBUG    posttroll.publisher] Publish heartbeat (min_interval is 30.0 sec)
[2021-12-01 20:09:04,889 DEBUG    paramiko.transport] [chan 16] Max packet out: 32768 bytes
[2021-12-01 20:09:04,889 DEBUG    paramiko.transport] Secsh channel 16 opened.
[2021-12-01 20:09:04,892 DEBUG    paramiko.transport] [chan 16] Sesch channel 16 request ok
[2021-12-01 20:09:05,092 DEBUG    paramiko.transport] [chan 16] EOF sent (16)
[2021-12-01 20:09:05,093 INFO     trollmoves.movers] Successfully copied /data/pytroll/nwcsaf/intermediate/ANC_remapped/S_NWC_textures_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc to scp://157.249.160.122/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf
[2021-12-01 20:09:05,093 DEBUG    trollmoves.movers] new_dest = ParseResult(scheme='scp', netloc='remotesensing@157.249.160.122', path='/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf', params='', query='', fragment='')
[2021-12-01 20:09:05,093 DEBUG    trollmoves.movers] Copying to: scp://157.249.160.122/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf
[2021-12-01 20:09:05,093 DEBUG    trollmoves.movers] Scheme = scp
[2021-12-01 20:09:05,093 DEBUG    trollmoves.movers] Destination: ParseResult(scheme='scp', netloc='remotesensing@157.249.160.122', path='/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf', params='', query='', fragment='')
[2021-12-01 20:09:05,093 DEBUG    trollmoves.movers] Destination username and passwd: remotesensing None
[2021-12-01 20:09:05,093 DEBUG    trollmoves.movers] Getting connection to remotesensing@157.249.160.122:22
[2021-12-01 20:09:05,093 DEBUG    trollmoves.movers] checking ssh connection
[2021-12-01 20:09:05,093 DEBUG    trollmoves.movers] SSH connection is active.
[2021-12-01 20:09:05,094 DEBUG    paramiko.transport] [chan 17] Max packet in: 32768 bytes
[2021-12-01 20:09:05,095 DEBUG    paramiko.transport] [chan 16] EOF received (16)
[2021-12-01 20:09:05,137 DEBUG    paramiko.transport] [chan 17] Max packet out: 32768 bytes
[2021-12-01 20:09:05,137 DEBUG    paramiko.transport] Secsh channel 17 opened.
[2021-12-01 20:09:05,139 DEBUG    paramiko.transport] [chan 17] Sesch channel 17 request ok
[2021-12-01 20:09:05,180 DEBUG    paramiko.transport] [chan 17] EOF sent (17)
[2021-12-01 20:09:05,180 INFO     trollmoves.movers] Successfully copied /data/pytroll/nwcsaf/intermediate/EMISS_remapped/S_NWC_emissivity_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc to scp://157.249.160.122/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf
[2021-12-01 20:09:05,181 DEBUG    trollmoves.movers] new_dest = ParseResult(scheme='scp', netloc='remotesensing@157.249.160.122', path='/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf', params='', query='', fragment='')
[2021-12-01 20:09:05,181 DEBUG    trollmoves.movers] Copying to: scp://157.249.160.122/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf
[2021-12-01 20:09:05,181 DEBUG    trollmoves.movers] Scheme = scp
[2021-12-01 20:09:05,181 DEBUG    trollmoves.movers] Destination: ParseResult(scheme='scp', netloc='remotesensing@157.249.160.122', path='/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf', params='', query='', fragment='')
[2021-12-01 20:09:05,181 DEBUG    trollmoves.movers] Destination username and passwd: remotesensing None
[2021-12-01 20:09:05,181 DEBUG    trollmoves.movers] Getting connection to remotesensing@157.249.160.122:22
[2021-12-01 20:09:05,181 DEBUG    trollmoves.movers] checking ssh connection
[2021-12-01 20:09:05,181 DEBUG    trollmoves.movers] SSH connection is active.
[2021-12-01 20:09:05,182 DEBUG    paramiko.transport] [chan 18] Max packet in: 32768 bytes
[2021-12-01 20:09:05,183 DEBUG    paramiko.transport] [chan 17] EOF received (17)
[2021-12-01 20:09:05,225 DEBUG    paramiko.transport] [chan 18] Max packet out: 32768 bytes
[2021-12-01 20:09:05,225 DEBUG    paramiko.transport] Secsh channel 18 opened.
[2021-12-01 20:09:05,228 DEBUG    paramiko.transport] [chan 18] Sesch channel 18 request ok
[2021-12-01 20:09:05,243 DEBUG    paramiko.transport] [chan 18] EOF sent (18)
[2021-12-01 20:09:05,244 INFO     trollmoves.movers] Successfully copied /data/pytroll/nwcsaf/intermediate/IMAGER_remapped/S_NWC_37refl_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc to scp://157.249.160.122/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf
[2021-12-01 20:09:05,245 DEBUG    trollmoves.server] Response: pytroll://PPSV2021/EARS/PRODUCTS dataset ubuntu@pps-v2021-a 2021-12-01T20:09:05.245150 v1.01 application/json {"antenna": "ears", "publish_topic": "/PPS-V2021/ears/processed", "station": "Oslo", "variant": "EARS", "geo_or_polar": "polar", "software": "NWCSAF-PPSv2021", "nameservers": ["192.168.10.9"], "module": "ppsCmaskPrepare", "pps_version": "v2021", "platform_name": "Metop-B", "orbit": 0, "sensor": "avhrr", "start_time": "2021-12-01T20:00:00", "end_time": "2021-12-01T20:00:59.800000", "file_was_already_processed": false, "status": "OK", "dataset": [{"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/ANC_remapped/S_NWC_thresholds_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_thresholds_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}, {"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/ANC_remapped/S_NWC_textures_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_textures_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}, {"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/EMISS_remapped/S_NWC_emissivity_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_emissivity_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}, {"uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/intermediate/IMAGER_remapped/S_NWC_37refl_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc", "uid": "S_NWC_37refl_metopb_00000_20211201T2000000Z_20211201T2000598Z.nc"}], "data_processing_level": "2", "format": "CF", "request_address": "157.249.98.10:9301", "destination": "scp://157.249.160.122/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf"}
[2021-12-01 20:09:05,247 DEBUG    paramiko.transport] [chan 18] EOF received (18)
```
```

**Comment by TAlonglong** [comment]
It looks like an additional messgae element `nameservers` was added by a misstake and this caused the specific client listner to crash. Dataset transfer works fint!

**Comment by mraspaud** [comment]
Thanks for the feedback. I understand that the message received by the move_it_server was not correct, but should the process here be a bit more robust against this kind of situations? do you have an example of the message that was received?

**Comment by TAlonglong** [comment]
Yes, but the problem is that my client config has a `nameservers` entry in the default section in addition to the config:
```
[DEFAULT]
nameservers = ppi-adm-a2

[pps-v2021-ears-products]
providers=157.249.98.10:9960
destination=scp://remotesensing@157.249.160.122/lustre/storeA/project/metproduction/products/satdata_polar/pps-v2021/ears/netcdf
login=remotesensing
topic=/PPSV2021/EARS/PRODUCTS
publish_port=0
heartbeat_alarm_scale=30
transfer_req_timeout=30
req_timeout=30
```

And when you get a message like this:
```
Dec 02 07:05:30 ppi-adm-a2 move_it_client.py[4579]: [2021-12-02 07:05:30,643 DEBUG    trollmoves.client] Receiving (SUB) pytroll://PPSV2021/EARS/PRODUCTS file ubuntu@pps-v2021-a 2021-12-02T07:05:30.150004 v1.01 application/json {"antenna": "ears", "publish_topic": "/PPS-V2021/ears/processed", "station": "Oslo", "variant": "EARS", "geo_or_polar": "polar", "software": "NWCSAF-PPSv2021", "nameservers": ["192.168.10.9"], "module": "ppsCtth", "pps_version": "v2021", "platform_name": "Suomi-NPP", "orbit": 0, "sensor": "viirs", "start_time": "2021-12-02T06:33:31", "end_time": "2021-12-02T06:34:55.200000", "file_was_already_processed": false, "status": "OK", "uri": "ssh://pps-v2021-a/data/pytroll/nwcsaf/export/S_NWC_CTTH_npp_00000_20211202T0633310Z_20211202T0634552Z.nc", "uid": "S_NWC_CTTH_npp_00000_20211202T0633310Z_20211202T0634552Z.nc", "data_processing_level": "2", "format": "CF", "request_address": "157.249.98.10:9301"}
```
The code
