### ISSUE TITLE
delete default set to bool False, but is handled as a string

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/trollmoves#141]
**Describe the bug**

```
Traceback (most recent call last):
  File "/software/miniconda/envs/pytroll/lib/python3.9/site-packages/trollmoves/server.py", line 210, in reply_and_send
    reply = fun(message)
  File "/software/miniconda/envs/pytroll/lib/python3.9/site-packages/trollmoves/server.py", line 131, in push
    new_msg = self._move_files(message)
  File "/software/miniconda/envs/pytroll/lib/python3.9/site-packages/trollmoves/server.py", line 148, in _move_files
    error_message = self._move_file(pathname, message, rel_path)
  File "/software/miniconda/envs/pytroll/lib/python3.9/site-packages/trollmoves/server.py", line 170, in _move_file
    self._add_to_deleter(pathname)
  File "/software/miniconda/envs/pytroll/lib/python3.9/site-packages/trollmoves/server.py", line 174, in _add_to_deleter
    if self._attrs.get('compression') or self._is_delete_set():
  File "/software/miniconda/envs/pytroll/lib/python3.9/site-packages/trollmoves/server.py", line 178, in _is_delete_set
    return self._attrs.get('delete', 'False').lower() in ["1", "yes", "true", "on"]
AttributeError: 'bool' object has no attribute 'lower'
```
**To Reproduce**
You need to run the server

**Expected behavior**
To work even if delete is not set

**Environment Info:**
 - OS: Linux
 - Trollmoves Version: main/master

**Comment by TAlonglong** [comment]
Problematic line is here: https://github.com/pytroll/trollmoves/blob/main/trollmoves/server.py#L596 where is handles the delete attribute as a string
