### ISSUE TITLE
local file copy needs unnecessary login option in move_it_client.ini

### ISSUE THREAD

**Issue by peters77** [pytroll/trollmoves#47]
If activating local file copy via `file://`  the client config needs an unnecessary login statement. So disable `#login = user` stalls the copy procedure.

**server.ini:**

[eumetcast_S3A]
origin = /home/cpeters/testdata/S3A_OL_1_EFR____{start_time:%Y%m%dT%H%M%S}_{end_time:%Y%m%dT%H%M%S}_{creation_time:%Y%m%dT%H%M%S}_{duration:4d}_{cycle:3d}_{relative_orbit:3d}_{frame:4d}_{centre:3s}_{platform_mode:1s}_{timeliness:2s}_{collection:3s}.SEN3.{compress}
request_port = 9096
publisher_port = 9010
info = sensor=olci
topic = /S3A/test
delete = True

**client.ini:** 

[eumetcast_S3A]
providers = smaug:9010
destination = /home/dir/test/
#login = user
topic = /S3A/test/
publish_port = 0

**log client:**

`[2019-10-22 17:14:35,078 DEBUG    posttroll.bbmcast] Started multicast group 225.0.0.212
[2019-10-22 17:14:35,079 DEBUG    trollmoves.client] Added eumetcast_S3A
[2019-10-22 17:14:35,079 DEBUG    trollmoves.client] Reloaded config from /home/cpeters/trollmoves/examples/move_it_client.ini
[2019-10-22 17:14:36,081 DEBUG    posttroll.publisher] Publish heartbeat (min_interval is 30.0 sec)
[2019-10-22 17:14:40,042 DEBUG    trollmoves.client] Receiving (SUB) pytroll://him8/test file cpeters@smaug 2019-10-22T15:14:40.027967 v1.01 application/json {"request_address": "192.168.1.159:9095", "uri": "/tmp/IMG_DK01B11_201910221505_006", "uid": "IMG_DK01B11_201910221505_006", "sensor": "ahi", "channel": "B11", "segment": "006.bz2", "compress": "", "time": "2019-10-22T15:05:00", "platform_name": "DK01"}
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/cpeters/anaconda2/envs/pytroll/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/cpeters/anaconda2/envs/pytroll/lib/python3.6/site-packages/trollmoves/client.py", line 183, in run
    self.callback(msg, *self.cargs, **self.ckwargs)
TypeError: request_push() missing 1 required positional argument: 'login'`

**Comment by bornagain1981** [comment]
Workaround: In the client ini file you leave the login row enable as default in the example 
login=user:pass

and your destination as follow 
destination = file:///media/....

3 

> ///

in front of your path

**Comment by pnuu** [comment]
Closed by #71
