### ISSUE TITLE
Error in recv_multipart leaves push-pull connection unusable

### ISSUE THREAD

**Issue by mraspaud** [pytroll/trollmoves#63]
It has been observed at SMHI that something the `recv_multipart` goes wrong here:
https://github.com/pytroll/trollmoves/blob/master/trollmoves/server.py#L273-L274

When this happens, the number of returned values changes, and an error ensues:
```python-traceback
[2020-05-11 06:12:26,756 DEBUG   ] Received a request
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/pytroll_fu/server.py", line 217, in run
    NOBLOCK)
ValueError: need more than 2 values to unpack
```

The server code should catch this problem and mitigate it nicely.

**Comment by pnuu** [comment]
Closed by combination of #71 and #82
